
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action BuildAction;

	private global::Gtk.Action ToolsAction;

	private global::Gtk.Action DeviceAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action OpenProjectAction;

	private global::Gtk.Action CreateProjectAction;

	private global::Gtk.Action AboutICodeAction;

	private global::Gtk.Action BuildProjectAction;

	private global::Gtk.Action ExtensionsAction;

	private global::Gtk.VBox container;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button6;

	private global::Gtk.ComboBox combobox4;

	private global::Gtk.VSeparator vseparator2;

	private global::Gtk.Fixed fixed6;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.EditAction = new global::Gtk.Action("EditAction", global::Mono.Unix.Catalog.GetString("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edit");
		w1.Add(this.EditAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("View");
		w1.Add(this.ViewAction, null);
		this.BuildAction = new global::Gtk.Action("BuildAction", global::Mono.Unix.Catalog.GetString("Build"), null, null);
		this.BuildAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Build");
		w1.Add(this.BuildAction, null);
		this.ToolsAction = new global::Gtk.Action("ToolsAction", global::Mono.Unix.Catalog.GetString("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tools");
		w1.Add(this.ToolsAction, null);
		this.DeviceAction = new global::Gtk.Action("DeviceAction", global::Mono.Unix.Catalog.GetString("Device"), null, null);
		this.DeviceAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Device");
		w1.Add(this.DeviceAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.OpenProjectAction = new global::Gtk.Action("OpenProjectAction", global::Mono.Unix.Catalog.GetString("Open project..."), null, null);
		this.OpenProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("DEBUG_LOAD_PROJECT");
		w1.Add(this.OpenProjectAction, null);
		this.CreateProjectAction = new global::Gtk.Action("CreateProjectAction", global::Mono.Unix.Catalog.GetString("Create project..."), null, null);
		this.CreateProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Create project...");
		w1.Add(this.CreateProjectAction, null);
		this.AboutICodeAction = new global::Gtk.Action("AboutICodeAction", global::Mono.Unix.Catalog.GetString("About iCode"), null, null);
		this.AboutICodeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About iCode");
		w1.Add(this.AboutICodeAction, null);
		this.BuildProjectAction = new global::Gtk.Action("BuildProjectAction", global::Mono.Unix.Catalog.GetString("Build project"), null, null);
		this.BuildProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Build project");
		w1.Add(this.BuildProjectAction, null);
		this.ExtensionsAction = new global::Gtk.Action("ExtensionsAction", global::Mono.Unix.Catalog.GetString("Extensions"), null, null);
		this.ExtensionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Extensions");
		w1.Add(this.ExtensionsAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("iCode");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("iCode.resources.images.icon.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.container = new global::Gtk.VBox();
		this.container.Name = "container";
		this.container.Spacing = 6;
		// Container child container.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction1' action='FileAction1'><menuitem name='OpenProjectAction' action='OpenProjectAction'/><menuitem name='CreateProjectAction' action='CreateProjectAction'/></menu><menu name='EditAction' action='EditAction'/><menu name='ViewAction' action='ViewAction'/><menu name='BuildAction' action='BuildAction'><menuitem name='BuildProjectAction' action='BuildProjectAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='ExtensionsAction' action='ExtensionsAction'/></menu><menu name='DeviceAction' action='DeviceAction'/><menu name='HelpAction' action='HelpAction'><menuitem name='AboutICodeAction' action='AboutICodeAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.container.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.container[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child container.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Launch");
		this.hbox2.Add(this.button6);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button6]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox4 = new global::Gtk.ComboBox();
		this.combobox4.Name = "combobox4";
		this.hbox2.Add(this.combobox4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.combobox4]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator();
		this.vseparator2.Name = "vseparator2";
		this.hbox2.Add(this.vseparator2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vseparator2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox2.Add(this.fixed6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed6]));
		w6.Position = 3;
		this.container.Add(this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.container[this.hbox2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child container.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ready");
		this.statusbar1.Add(this.label1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.container.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.container[this.statusbar1]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.container);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 867;
		this.DefaultHeight = 664;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenProjectAction.Activated += new global::System.EventHandler(this.LoadProjectActivated);
		this.CreateProjectAction.Activated += new global::System.EventHandler(this.CreateProject);
	}
}
