// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[GLib.GType (typeof (GtkSource.BracketMatchTypeGType))]
	public enum BracketMatchType {

		None = 0,
		OutOfRange = 1,
		NotFound = 2,
		Found = 3,
	}

	internal class BracketMatchTypeGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_bracket_match_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_bracket_match_type_get_type ());
			}
		}
	}
#endregion
}
