// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void BracketMatchedHandler(object o, BracketMatchedArgs args);

	public class BracketMatchedArgs : GLib.SignalArgs {
		public Gtk.TextIter Iter{
			get {
				return (Gtk.TextIter) Args [0];
			}
		}

		public GtkSource.BracketMatchType State{
			get {
				return (GtkSource.BracketMatchType) Args [1];
			}
		}

	}
}
