// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[GLib.GType (typeof (GtkSource.ChangeCaseTypeGType))]
	public enum ChangeCaseType {

		Lower = 0,
		Upper = 1,
		Toggle = 2,
		Title = 3,
	}

	internal class ChangeCaseTypeGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_change_case_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_change_case_type_get_type ());
			}
		}
	}
#endregion
}
