// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	public partial class Constants {

#endregion
	}
}
