// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	public partial class FileLoader : GLib.Object {

		public FileLoader (IntPtr raw) : base(raw) {}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_file_loader_new(IntPtr buffer, IntPtr file);

		public FileLoader (GtkSource.Buffer buffer, GtkSource.File file) : base (IntPtr.Zero)
		{
			if (GetType () != typeof (FileLoader)) {
				var vals = new List<GLib.Value> ();
				var names = new List<string> ();
				if (buffer != null) {
					names.Add ("buffer");
					vals.Add (new GLib.Value (buffer));
				}
				if (file != null) {
					names.Add ("file");
					vals.Add (new GLib.Value (file));
				}
				CreateNativeObject (names.ToArray (), vals.ToArray ());
				return;
			}
			Raw = gtk_source_file_loader_new(buffer == null ? IntPtr.Zero : buffer.Handle, file == null ? IntPtr.Zero : file.Handle);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_file_loader_get_buffer(IntPtr raw);

		[GLib.Property ("buffer")]
		public GtkSource.Buffer Buffer {
			get  {
				IntPtr raw_ret = gtk_source_file_loader_get_buffer(Handle);
				GtkSource.Buffer ret = GLib.Object.GetObject(raw_ret) as GtkSource.Buffer;
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_file_loader_get_file(IntPtr raw);

		[GLib.Property ("file")]
		public GtkSource.File File {
			get  {
				IntPtr raw_ret = gtk_source_file_loader_get_file(Handle);
				GtkSource.File ret = GLib.Object.GetObject(raw_ret) as GtkSource.File;
				return ret;
			}
		}

		[DllImport ("libgtksourcesharpglue-4.6.0.so")]
		extern static uint gtksourcesharp_gtksource_fileloader_get_parent_offset ();

		static uint parent_offset = gtksourcesharp_gtksource_fileloader_get_parent_offset ();
		public GLib.Object Parent {
			get {
				unsafe {
					IntPtr* raw_ptr = (IntPtr*)(((byte*)Handle) + parent_offset);
					return GLib.Object.GetObject ((*raw_ptr));
				}
			}
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceFileLoaderClass {
			[MarshalAs (UnmanagedType.ByValArray, SizeConst=10)]
			public object[] Padding;
		}

		static uint class_offset = 0;
		static Dictionary<GLib.GType, GtkSourceFileLoaderClass> class_structs;

		static GtkSourceFileLoaderClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceFileLoaderClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceFileLoaderClass class_struct = (GtkSourceFileLoaderClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceFileLoaderClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceFileLoaderClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_file_loader_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_source_file_loader_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern int gtk_source_file_loader_get_compression_type(IntPtr raw);

		public GtkSource.CompressionType CompressionType { 
			get {
				int raw_ret = gtk_source_file_loader_get_compression_type(Handle);
				GtkSource.CompressionType ret = (GtkSource.CompressionType) raw_ret;
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_file_loader_get_encoding(IntPtr raw);

		public GtkSource.Encoding Encoding { 
			get {
				IntPtr raw_ret = gtk_source_file_loader_get_encoding(Handle);
				GtkSource.Encoding ret = GtkSource.Encoding.New (raw_ret);
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern int gtk_source_file_loader_get_newline_type(IntPtr raw);

		public GtkSource.NewlineType NewlineType { 
			get {
				int raw_ret = gtk_source_file_loader_get_newline_type(Handle);
				GtkSource.NewlineType ret = (GtkSource.NewlineType) raw_ret;
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_file_loader_set_candidate_encodings(IntPtr raw, IntPtr candidate_encodings);

		public GLib.SList CandidateEncodings { 
			set {
				gtk_source_file_loader_set_candidate_encodings(Handle, value == null ? IntPtr.Zero : value.Handle);
			}
		}

#endregion
	}
}
