// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	public partial class GutterRendererPixbuf : GtkSource.GutterRenderer {

		public GutterRendererPixbuf (IntPtr raw) : base(raw) {}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_gutter_renderer_pixbuf_new();

		public GutterRendererPixbuf () : base (IntPtr.Zero)
		{
			if (GetType () != typeof (GutterRendererPixbuf)) {
				CreateNativeObject (new string [0], new GLib.Value[0]);
				return;
			}
			Raw = gtk_source_gutter_renderer_pixbuf_new();
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_gutter_renderer_pixbuf_get_icon_name(IntPtr raw);

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_gutter_renderer_pixbuf_set_icon_name(IntPtr raw, IntPtr icon_name);

		[GLib.Property ("icon-name")]
		public string IconName {
			get  {
				IntPtr raw_ret = gtk_source_gutter_renderer_pixbuf_get_icon_name(Handle);
				string ret = GLib.Marshaller.Utf8PtrToString (raw_ret);
				return ret;
			}
			set  {
				IntPtr native_value = GLib.Marshaller.StringToPtrGStrdup (value);
				gtk_source_gutter_renderer_pixbuf_set_icon_name(Handle, native_value);
				GLib.Marshaller.Free (native_value);
			}
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceGutterRendererPixbufClass {
			[MarshalAs (UnmanagedType.ByValArray, SizeConst=10)]
			private object[] Padding;
		}

		static uint class_offset = ((GLib.GType) typeof (GtkSource.GutterRenderer)).GetClassSize ();
		static Dictionary<GLib.GType, GtkSourceGutterRendererPixbufClass> class_structs;

		static GtkSourceGutterRendererPixbufClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceGutterRendererPixbufClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceGutterRendererPixbufClass class_struct = (GtkSourceGutterRendererPixbufClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceGutterRendererPixbufClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceGutterRendererPixbufClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_gutter_renderer_pixbuf_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_source_gutter_renderer_pixbuf_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}


		static GutterRendererPixbuf ()
		{
			ObjectManager.Initialize ();
		}
#endregion
	}
}
