// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[Flags]
	[GLib.GType (typeof (GtkSource.GutterRendererStateGType))]
	public enum GutterRendererState {

		Normal = 0,
		Cursor = 1,
		Prelit = 2,
		Selected = 4,
	}

	internal class GutterRendererStateGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_gutter_renderer_state_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_gutter_renderer_state_get_type ());
			}
		}
	}
#endregion
}
