// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	public partial interface IStyleSchemeChooser : GLib.IWrapper {

		GtkSource.StyleScheme StyleScheme {
			get; set;
		}
	}

	[GLib.GInterface (typeof (StyleSchemeChooserAdapter))]
	public partial interface IStyleSchemeChooserImplementor : GLib.IWrapper {

		[GLib.Property ("style-scheme")]
		GtkSource.StyleScheme StyleScheme {
			get; set;
		}
	}
#endregion
}
