// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void LineMarkActivatedHandler(object o, LineMarkActivatedArgs args);

	public class LineMarkActivatedArgs : GLib.SignalArgs {
		public Gtk.TextIter Iter{
			get {
				return (Gtk.TextIter) Args [0];
			}
		}

		public Gdk.Event Event{
			get {
				return (Gdk.Event) Args [1];
			}
		}

	}
}
