// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void MoveLinesHandler(object o, MoveLinesArgs args);

	public class MoveLinesArgs : GLib.SignalArgs {
		public bool Down{
			get {
				return (bool) Args [0];
			}
		}

	}
}
