// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void MoveToMatchingBracketHandler(object o, MoveToMatchingBracketArgs args);

	public class MoveToMatchingBracketArgs : GLib.SignalArgs {
		public bool ExtendSelection{
			get {
				return (bool) Args [0];
			}
		}

	}
}
