// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[GLib.GType (typeof (GtkSource.NewlineTypeGType))]
	public enum NewlineType {

		Lf = 0,
		Cr = 1,
		CrLf = 2,
	}

	internal class NewlineTypeGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_newline_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_newline_type_get_type ());
			}
		}
	}
#endregion
}
