// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void PopulateContextHandler(object o, PopulateContextArgs args);

	public class PopulateContextArgs : GLib.SignalArgs {
		public GtkSource.CompletionContext Context{
			get {
				return (GtkSource.CompletionContext) Args [0];
			}
		}

	}
}
