// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void QueryDataEventHandler(object o, QueryDataEventArgs args);

	public class QueryDataEventArgs : GLib.SignalArgs {
		public Gtk.TextIter Start{
			get {
				return (Gtk.TextIter) Args [0];
			}
		}

		public Gtk.TextIter End{
			get {
				return (Gtk.TextIter) Args [1];
			}
		}

		public GtkSource.GutterRendererState State{
			get {
				return (GtkSource.GutterRendererState) Args [2];
			}
		}

	}
}
