// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void QueryTooltipMarkupHandler(object o, QueryTooltipMarkupArgs args);

	public class QueryTooltipMarkupArgs : GLib.SignalArgs {
		public GtkSource.Mark Mark{
			get {
				return (GtkSource.Mark) Args [0];
			}
		}

	}
}
