// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void QueryTooltipEventHandler(object o, QueryTooltipEventArgs args);

	public class QueryTooltipEventArgs : GLib.SignalArgs {
		public Gtk.TextIter Iter{
			get {
				return (Gtk.TextIter) Args [0];
			}
		}

		public Gdk.Rectangle Area{
			get {
				return (Gdk.Rectangle) Args [1];
			}
		}

		public int X{
			get {
				return (int) Args [2];
			}
		}

		public int Y{
			get {
				return (int) Args [3];
			}
		}

		public Gtk.Tooltip Tooltip{
			get {
				return (Gtk.Tooltip) Args [4];
			}
		}

	}
}
