// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[GLib.GType (typeof (GtkSource.SmartHomeEndTypeGType))]
	public enum SmartHomeEndType {

		Disabled = 0,
		Before = 1,
		After = 2,
		Always = 3,
	}

	internal class SmartHomeEndTypeGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_smart_home_end_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_smart_home_end_type_get_type ());
			}
		}
	}
#endregion
}
