// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace iCode.Native.GtkSource {
	public delegate void SmartHomeEndHandler(object o, SmartHomeEndArgs args);

	public class SmartHomeEndArgs : GLib.SignalArgs {
		public Gtk.TextIter Iter{
			get {
				return (Gtk.TextIter) Args [0];
			}
		}

		public int Count{
			get {
				return (int) Args [1];
			}
		}

	}
}
