// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[Flags]
	[GLib.GType (typeof (GtkSource.SpaceLocationFlagsGType))]
	public enum SpaceLocationFlags {

		None = 0,
		Leading = 1,
		InsideText = 2,
		Trailing = 4,
		All = 7,
	}

	internal class SpaceLocationFlagsGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_space_location_flags_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_space_location_flags_get_type ());
			}
		}
	}
#endregion
}
