// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[Flags]
	[GLib.GType (typeof (GtkSource.SpaceTypeFlagsGType))]
	public enum SpaceTypeFlags {

		None = 0,
		Space = 1,
		Tab = 2,
		Newline = 4,
		Nbsp = 8,
		All = 15,
	}

	internal class SpaceTypeFlagsGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_space_type_flags_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_space_type_flags_get_type ());
			}
		}
	}
#endregion
}
