// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	public partial class StyleSchemeManager : GLib.Object {

		public StyleSchemeManager (IntPtr raw) : base(raw) {}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_new();

		public StyleSchemeManager () : base (IntPtr.Zero)
		{
			if (GetType () != typeof (StyleSchemeManager)) {
				CreateNativeObject (new string [0], new GLib.Value[0]);
				return;
			}
			Raw = gtk_source_style_scheme_manager_new();
		}

		[DllImport ("libgtksourcesharpglue-4.6.0.so")]
		extern static uint gtksourcesharp_gtksource_styleschememanager_get_parent_offset ();

		static uint parent_offset = gtksourcesharp_gtksource_styleschememanager_get_parent_offset ();
		public GLib.Object Parent {
			get {
				unsafe {
					IntPtr* raw_ptr = (IntPtr*)(((byte*)Handle) + parent_offset);
					return GLib.Object.GetObject ((*raw_ptr));
				}
			}
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceStyleSchemeManagerClass {
			[MarshalAs (UnmanagedType.ByValArray, SizeConst=10)]
			public object[] Padding;
		}

		static uint class_offset = 0;
		static Dictionary<GLib.GType, GtkSourceStyleSchemeManagerClass> class_structs;

		static GtkSourceStyleSchemeManagerClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceStyleSchemeManagerClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceStyleSchemeManagerClass class_struct = (GtkSourceStyleSchemeManagerClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceStyleSchemeManagerClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceStyleSchemeManagerClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_default();

		public static GtkSource.StyleSchemeManager Default { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_default();
				GtkSource.StyleSchemeManager ret = GLib.Object.GetObject(raw_ret) as GtkSource.StyleSchemeManager;
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_append_search_path(IntPtr raw, IntPtr path);

		public void AppendSearchPath(string path) {
			IntPtr native_path = GLib.Marshaller.StringToPtrGStrdup (path);
			gtk_source_style_scheme_manager_append_search_path(Handle, native_path);
			GLib.Marshaller.Free (native_path);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_force_rescan(IntPtr raw);

		public void ForceRescan() {
			gtk_source_style_scheme_manager_force_rescan(Handle);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_scheme(IntPtr raw, IntPtr scheme_id);

		public GtkSource.StyleScheme GetScheme(string scheme_id) {
			IntPtr native_scheme_id = GLib.Marshaller.StringToPtrGStrdup (scheme_id);
			IntPtr raw_ret = gtk_source_style_scheme_manager_get_scheme(Handle, native_scheme_id);
			GtkSource.StyleScheme ret = GLib.Object.GetObject(raw_ret) as GtkSource.StyleScheme;
			GLib.Marshaller.Free (native_scheme_id);
			return ret;
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_scheme_ids(IntPtr raw);

		public string[] SchemeIds { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_scheme_ids(Handle);
				string[] ret = GLib.Marshaller.NullTermPtrToStringArray (raw_ret, false);
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_search_path(IntPtr raw);

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_set_search_path(IntPtr raw, IntPtr[] path);

		public string[] SearchPath { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_search_path(Handle);
				string[] ret = GLib.Marshaller.NullTermPtrToStringArray (raw_ret, false);
				return ret;
			}
			set {
				int cnt_value = value == null ? 0 : value.Length;
				IntPtr[] native_value = new IntPtr [cnt_value + 1];
				for (int i = 0; i < cnt_value; i++)
					native_value [i] = GLib.Marshaller.StringToPtrGStrdup (value[i]);
				native_value [cnt_value] = IntPtr.Zero;
				gtk_source_style_scheme_manager_set_search_path(Handle, native_value);
				for (int i = 0; i < native_value.Length - 1; i++) {
					value [i] = GLib.Marshaller.Utf8PtrToString (native_value[i]);
					GLib.Marshaller.Free (native_value[i]);
				}
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_prepend_search_path(IntPtr raw, IntPtr path);

		public void PrependSearchPath(string path) {
			IntPtr native_path = GLib.Marshaller.StringToPtrGStrdup (path);
			gtk_source_style_scheme_manager_prepend_search_path(Handle, native_path);
			GLib.Marshaller.Free (native_path);
		}

#endregion
	}
}
