// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

using System;
using System.Runtime.InteropServices;

namespace iCode.Native.GtkSource {
	#region Autogenerated code
	[GLib.GType (typeof (GtkSource.ViewGutterPositionGType))]
	public enum ViewGutterPosition {

		Lines = -30,
		Marks = -20,
	}

	internal class ViewGutterPositionGType {
		[DllImport ("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_view_gutter_position_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (gtk_source_view_gutter_position_get_type ());
			}
		}
	}
#endregion
}
