// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public partial class DefinitionChild : GLib.Opaque {

		public DefinitionChild(IntPtr raw) : base(raw) {}

#endregion
	}
}
