// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

#region Autogenerated code
	public partial interface ISourceEngine : GLib.IWrapper {

	}

	[GLib.GInterface (typeof (SourceEngineAdapter))]
	public partial interface ISourceEngineImplementor : GLib.IWrapper {

	}
#endregion
}
