// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

#region Autogenerated code
	public partial interface ISourceCompletionProposal : GLib.IWrapper {

		event System.EventHandler Changed;
		void Changed();
		bool Equal(Gtk.ISourceCompletionProposal other);
		string IconName { 
			get;
		}
		string Info { 
			get;
		}
		string Label { 
			get;
		}
		string Markup { 
			get;
		}
		string Text { 
			get;
		}
		uint Hash();
	}

	[GLib.GInterface (typeof (SourceCompletionProposalAdapter))]
	public partial interface ISourceCompletionProposalImplementor : GLib.IWrapper {

		string Label { get; }
		string Markup { get; }
		string Text { get; }
		string IconName { get; }
		string Info { get; }
		uint Hash ();
		bool Equal (Gtk.ISourceCompletionProposal other);
	}
#endregion
}
