// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

#region Autogenerated code
	public partial interface ISourceCompletionProvider : GLib.IWrapper {

		Gtk.SourceCompletionActivation Activation { 
			get;
		}
		string IconName { 
			get;
		}
		int InteractiveDelay { 
			get;
		}
		string Name { 
			get;
		}
		int Priority { 
			get;
		}
		bool Match(Gtk.SourceCompletionContext context);
		void Populate(Gtk.SourceCompletionContext context);
		void UpdateInfo(Gtk.ISourceCompletionProposal proposal, Gtk.SourceCompletionInfo info);
	}

	[GLib.GInterface (typeof (SourceCompletionProviderAdapter))]
	public partial interface ISourceCompletionProviderImplementor : GLib.IWrapper {

		string Name { get; }
		string IconName { get; }
		void Populate (Gtk.SourceCompletionContext context);
		bool Match (Gtk.SourceCompletionContext context);
		Gtk.SourceCompletionActivation Activation { get; }
		void UpdateInfo (Gtk.ISourceCompletionProposal proposal, Gtk.SourceCompletionInfo info);
		int InteractiveDelay { get; }
		int Priority { get; }
	}
#endregion
}
