// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

#region Autogenerated code
	public partial interface ISourceUndoManager : GLib.IWrapper {

		void BeginNotUndoableAction();
		bool CanRedo();
		void CanRedoChanged();
		bool CanUndo();
		void CanUndoChanged();
		void EndNotUndoableAction();
		void Redo();
		void Undo();
	}

	[GLib.GInterface (typeof (SourceUndoManagerAdapter))]
	public partial interface ISourceUndoManagerImplementor : GLib.IWrapper {

		bool CanUndo ();
		bool CanRedo ();
		void Undo ();
		void Redo ();
		void BeginNotUndoableAction ();
		void EndNotUndoableAction ();
		void CanUndoChanged ();
		void CanRedoChanged ();
	}
#endregion
}
