// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

#region Autogenerated code
	public partial interface ISourceStyleSchemeChooser : GLib.IWrapper {

		Gtk.SourceStyleScheme StyleScheme {
			get; set;
		}
	}

	[GLib.GInterface (typeof (SourceStyleSchemeChooserAdapter))]
	public partial interface ISourceStyleSchemeChooserImplementor : GLib.IWrapper {

		Gtk.SourceStyleScheme StyleScheme { get; set; }
		[GLib.Property ("style-scheme")]
		Gtk.SourceStyleScheme StyleScheme {
			get; set;
		}
	}
#endregion
}
