// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;

	public delegate void QueryTooltipMarkupHandler(object o, QueryTooltipMarkupArgs args);

	public class QueryTooltipMarkupArgs : GLib.SignalArgs {
		public Gtk.SourceMark P0{
			get {
				return (Gtk.SourceMark) Args [0];
			}
		}

	}
}
