// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public partial class SourcePixbufHelper : GLib.Opaque {

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_pixbuf_helper_get_icon_name(IntPtr raw);

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_pixbuf_helper_set_icon_name(IntPtr raw, IntPtr icon_name);

		public string IconName { 
			get {
				IntPtr raw_ret = gtk_source_pixbuf_helper_get_icon_name(Handle);
				string ret = GLib.Marshaller.Utf8PtrToString (raw_ret);
				return ret;
			}
			set {
				IntPtr native_value = GLib.Marshaller.StringToPtrGStrdup (value);
				gtk_source_pixbuf_helper_set_icon_name(Handle, native_value);
				GLib.Marshaller.Free (native_value);
			}
		}

		public SourcePixbufHelper(IntPtr raw) : base(raw) {}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_pixbuf_helper_new();

		public SourcePixbufHelper () 
		{
			Raw = gtk_source_pixbuf_helper_new();
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_pixbuf_helper_free(IntPtr raw);

		protected override void Free (IntPtr raw)
		{
			gtk_source_pixbuf_helper_free (raw);
		}

		class FinalizerInfo {
			IntPtr handle;

			public FinalizerInfo (IntPtr handle)
			{
				this.handle = handle;
			}

			public bool Handler ()
			{
				gtk_source_pixbuf_helper_free (handle);
				return false;
			}
		}

		~SourcePixbufHelper ()
		{
			if (!Owned)
				return;
			FinalizerInfo info = new FinalizerInfo (Handle);
			GLib.Timeout.Add (50, new GLib.TimeoutHandler (info.Handler));
		}

#endregion
	}
}
