// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public partial class SourceBufferInputStream {

		public SourceBufferInputStream (IntPtr raw) : base(raw) {}

		protected SourceBufferInputStream() : base(IntPtr.Zero)
		{
			CreateNativeObject (new string [0], new GLib.Value [0]);
		}

		[GLib.Property ("newline-type")]
		public Gtk.SourceNewlineType NewlineType {
			get {
				GLib.Value val = GetProperty ("newline-type");
				Gtk.SourceNewlineType ret = (Gtk.SourceNewlineType) (Enum) val;
				val.Dispose ();
				return ret;
			}
		}

		[GLib.Property ("add-trailing-newline")]
		public bool AddTrailingNewline {
			get {
				GLib.Value val = GetProperty ("add-trailing-newline");
				bool ret = (bool) val;
				val.Dispose ();
				return ret;
			}
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceBufferInputStreamClass {
		}

		static uint class_offset = 0;
		static Dictionary<GLib.GType, GtkSourceBufferInputStreamClass> class_structs;

		static GtkSourceBufferInputStreamClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceBufferInputStreamClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceBufferInputStreamClass class_struct = (GtkSourceBufferInputStreamClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceBufferInputStreamClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceBufferInputStreamClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

#endregion
	}
}
