// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum SourceChangeCaseType {

		Lower,
		Upper,
		Toggle,
		Title,
	}
#endregion
}
