// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum SourceViewGutterPosition {

		Lines = -30,
		Marks = -20,
	}
#endregion
}
