// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceSortFlags {

		None,
		CaseSensitive = 1 << 0,
		ReverseOrder = 1 << 1,
		RemoveDuplicates = 1 << 2,
	}
#endregion
}
