// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceGutterRendererState {

		Normal,
		Cursor = 1 << 0,
		Prelit = 1 << 1,
		Selected = 1 << 2,
	}
#endregion
}
