// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public partial class SourceStyleSchemeManager : GLib.Object {

		public SourceStyleSchemeManager (IntPtr raw) : base(raw) {}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_new();

		public SourceStyleSchemeManager () : base (IntPtr.Zero)
		{
			if (GetType () != typeof (SourceStyleSchemeManager)) {
				CreateNativeObject (new string [0], new GLib.Value[0]);
				return;
			}
			Raw = gtk_source_style_scheme_manager_new();
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_search_path(IntPtr raw);

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_set_search_path(IntPtr raw, IntPtr path);

		[GLib.Property ("search-path")]
		public string SearchPath {
			get  {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_search_path(Handle);
				string ret = GLib.Marshaller.Utf8PtrToString (raw_ret);
				return ret;
			}
			set  {
				gtk_source_style_scheme_manager_set_search_path(Handle, GLib.Marshaller.StringToPtrGStrdup(value));
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_scheme_ids(IntPtr raw);

		[GLib.Property ("scheme-ids")]
		public string SchemeIds {
			get  {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_scheme_ids(Handle);
				string ret = GLib.Marshaller.Utf8PtrToString (raw_ret);
				return ret;
			}
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceStyleSchemeManagerClass {
			[MarshalAs (UnmanagedType.ByValArray, SizeConst=10)]
			private IntPtr[] Padding;
		}

		static uint class_offset = ((GLib.GType) typeof (GLib.Object)).GetClassSize ();
		static Dictionary<GLib.GType, GtkSourceStyleSchemeManagerClass> class_structs;

		static GtkSourceStyleSchemeManagerClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceStyleSchemeManagerClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceStyleSchemeManagerClass class_struct = (GtkSourceStyleSchemeManagerClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceStyleSchemeManagerClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceStyleSchemeManagerClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_append_search_path(IntPtr raw, IntPtr path);

		public void AppendSearchPath(string path) {
			IntPtr native_path = GLib.Marshaller.StringToPtrGStrdup (path);
			gtk_source_style_scheme_manager_append_search_path(Handle, native_path);
			GLib.Marshaller.Free (native_path);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_force_rescan(IntPtr raw);

		public void ForceRescan() {
			gtk_source_style_scheme_manager_force_rescan(Handle);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_default();

		public static Gtk.SourceStyleSchemeManager Default { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_default();
				Gtk.SourceStyleSchemeManager ret = GLib.Object.GetObject(raw_ret) as Gtk.SourceStyleSchemeManager;
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_scheme(IntPtr raw, IntPtr scheme_id);

		public Gtk.SourceStyleScheme GetScheme(string scheme_id) {
			IntPtr native_scheme_id = GLib.Marshaller.StringToPtrGStrdup (scheme_id);
			IntPtr raw_ret = gtk_source_style_scheme_manager_get_scheme(Handle, native_scheme_id);
			Gtk.SourceStyleScheme ret = GLib.Object.GetObject(raw_ret) as Gtk.SourceStyleScheme;
			GLib.Marshaller.Free (native_scheme_id);
			return ret;
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_style_scheme_manager_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_source_style_scheme_manager_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_style_scheme_manager_prepend_search_path(IntPtr raw, IntPtr path);

		public void PrependSearchPath(string path) {
			IntPtr native_path = GLib.Marshaller.StringToPtrGStrdup (path);
			gtk_source_style_scheme_manager_prepend_search_path(Handle, native_path);
			GLib.Marshaller.Free (native_path);
		}

#endregion
	}
}
