// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceSpaceLocationFlags {

		None,
		Leading = 1 << 0,
		InsideText = 1 << 1,
		Trailing = 1 << 2,
		All = 0x7,
	}
#endregion
}
