// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceContextFlags {

		ExtendParent = 1 << 0,
		EndParent = 1 << 1,
		EndAtLineEnd = 1 << 2,
		FirstLineOnly = 1 << 3,
		OnceOnly = 1 << 4,
		StyleInside = 1 << 5,
	}
#endregion
}
