// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public partial class SourceCompletionContext : GLib.InitiallyUnowned {

		public SourceCompletionContext (IntPtr raw) : base(raw) {}

		protected SourceCompletionContext() : base(IntPtr.Zero)
		{
			CreateNativeObject (new string [0], new GLib.Value [0]);
		}

		[GLib.Property ("completion")]
		public Gtk.SourceCompletion Completion {
			get {
				GLib.Value val = GetProperty ("completion");
				Gtk.SourceCompletion ret = (Gtk.SourceCompletion) val;
				val.Dispose ();
				return ret;
			}
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern int gtk_source_completion_context_get_activation(IntPtr raw);

		[GLib.Property ("activation")]
		public Gtk.SourceCompletionActivation Activation {
			get  {
				int raw_ret = gtk_source_completion_context_get_activation(Handle);
				Gtk.SourceCompletionActivation ret = (Gtk.SourceCompletionActivation) raw_ret;
				return ret;
			}
			set {
				GLib.Value val = new GLib.Value((Enum) value);
				SetProperty("activation", val);
				val.Dispose ();
			}
		}

		[GLib.Signal("cancelled")]
		public event System.EventHandler Cancelled {
			add {
				this.AddSignalHandler ("cancelled", value);
			}
			remove {
				this.RemoveSignalHandler ("cancelled", value);
			}
		}

		static CancelledNativeDelegate Cancelled_cb_delegate;
		static CancelledNativeDelegate CancelledVMCallback {
			get {
				if (Cancelled_cb_delegate == null)
					Cancelled_cb_delegate = new CancelledNativeDelegate (Cancelled_cb);
				return Cancelled_cb_delegate;
			}
		}

		static void OverrideCancelled (GLib.GType gtype)
		{
			OverrideCancelled (gtype, CancelledVMCallback);
		}

		static void OverrideCancelled (GLib.GType gtype, CancelledNativeDelegate callback)
		{
			GtkSourceCompletionContextClass class_iface = GetClassStruct (gtype, false);
			class_iface.Cancelled = callback;
			OverrideClassStruct (gtype, class_iface);
		}

		[UnmanagedFunctionPointer (CallingConvention.Cdecl)]
		delegate void CancelledNativeDelegate (IntPtr inst);

		static void Cancelled_cb (IntPtr inst)
		{
			try {
				SourceCompletionContext __obj = GLib.Object.GetObject (inst, false) as SourceCompletionContext;
				__obj.OnCancelled ();
			} catch (Exception e) {
				GLib.ExceptionManager.RaiseUnhandledException (e, false);
			}
		}

		[GLib.DefaultSignalHandler(Type=typeof(Gtk.SourceCompletionContext), ConnectionMethod="OverrideCancelled")]
		protected virtual void OnCancelled ()
		{
			InternalCancelled ();
		}

		private void InternalCancelled ()
		{
			CancelledNativeDelegate unmanaged = GetClassStruct (this.LookupGType ().GetThresholdType (), true).Cancelled;
			if (unmanaged == null) return;

			unmanaged (this.Handle);
		}

		[StructLayout (LayoutKind.Sequential)]
		struct GtkSourceCompletionContextClass {
			public CancelledNativeDelegate Cancelled;
			[MarshalAs (UnmanagedType.ByValArray, SizeConst=10)]
			private IntPtr[] Padding;
		}

		static uint class_offset = ((GLib.GType) typeof (GLib.InitiallyUnowned)).GetClassSize ();
		static Dictionary<GLib.GType, GtkSourceCompletionContextClass> class_structs;

		static GtkSourceCompletionContextClass GetClassStruct (GLib.GType gtype, bool use_cache)
		{
			if (class_structs == null)
				class_structs = new Dictionary<GLib.GType, GtkSourceCompletionContextClass> ();

			if (use_cache && class_structs.ContainsKey (gtype))
				return class_structs [gtype];
			else {
				IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
				GtkSourceCompletionContextClass class_struct = (GtkSourceCompletionContextClass) Marshal.PtrToStructure (class_ptr, typeof (GtkSourceCompletionContextClass));
				if (use_cache)
					class_structs.Add (gtype, class_struct);
				return class_struct;
			}
		}

		static void OverrideClassStruct (GLib.GType gtype, GtkSourceCompletionContextClass class_struct)
		{
			IntPtr class_ptr = new IntPtr (gtype.GetClassPtr ().ToInt64 () + class_offset);
			Marshal.StructureToPtr (class_struct, class_ptr, false);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern void gtk_source_completion_context_add_proposals(IntPtr raw, IntPtr provider, IntPtr proposals, bool finished);

		public void AddProposals(Gtk.ISourceCompletionProvider provider, GLib.List proposals, bool finished) {
			gtk_source_completion_context_add_proposals(Handle, provider == null ? IntPtr.Zero : ((provider is GLib.Object) ? (provider as GLib.Object).Handle : (provider as Gtk.SourceCompletionProviderAdapter).Handle), proposals == null ? IntPtr.Zero : proposals.Handle, finished);
		}

		[DllImport("gtksourceview-4", CallingConvention = CallingConvention.Cdecl)]
		static extern IntPtr gtk_source_completion_context_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_source_completion_context_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

#endregion
	}
}
