// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceContextRefOptions {

		IgnoreStyle = 1 << 0,
		OverrideStyle = 1 << 1,
		RefOriginal = 1 << 2,
	}
#endregion
}
