// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum SourceFileSaverFlags {

		None,
		IgnoreInvalidChars = 1 << 0,
		IgnoreModificationTime = 1 << 1,
		CreateBackup = 1 << 2,
	}
#endregion
}
